import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.scss";
import { Toaster } from "react-hot-toast";
import Navbar from "./components/Navbar";
import IdentityProvider from "./identity-provider";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: `Films ${process.env.NEXT_PUBLIC_COMPANY_NAME}`,
    description: "Generated by create next app",
};

async function getChannelName() {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL_API}/people/1/`, { cache: "no-store" });
    if (!res.ok) throw new Error("Failed to fetch data");
    return res.json();
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const data = await getChannelName();

    return (
        <html lang="en">
            <body className={gabarito.className}>
                <IdentityProvider value={data.name}>
                    <Navbar />
                    <Toaster />
                    {children}
                </IdentityProvider>
            </body>
        </html>
    );
}
